### ISSUE TITLE
cubids-purge text file to remove multiple files

### ISSUE THREAD

**Issue by nguyenandi** [PennLINC/CuBIDS#248]
I am following the below guide and am unsure how to remove multiple files at once using cubids-purge. I am not sure if it is my text format or if something is wrong with my txt file. could you please see my txt file attached and assist?

[no_DWI.txt](https://github.com/PennLINC/CuBIDS/files/10549148/no_DWI.txt)

cubids-purge requires as input a list of files to cleanly “purge” from the dataset. You can create this file in any text editor, as long as it is saved as plain text .txt. For this example, we created the following file:

… code-block:: console

/AN/EXAMPLE/PATH/CuBIDS_Test/BIDS_Dataset_Datalad/sub-02/ses-phdiff/func/sub-02_ses-phdiff_task-rest_bold.nii.gz

and saved it in our CuBIDS_Test directory.

To safely purge this file from the dataset, run:

cubids-purge BIDS_Dataset_DataLad no_ped.txt --use-datalad

**Comment by nguyenandi** [comment]
![Screenshot 2023-01-31 at 12 35 44 PM](https://user-images.githubusercontent.com/117756195/215838473-c3168e89-8601-459a-ac7a-c86d7ab23ac6.png)
I am running cubids from a server. Attached is the message I received after running cubids-purge

**Comment by araikes** [comment]
Bump for this @scovitz. I'm running into a similar problem, even when specifying a singular file path rather than folder.

**Comment by araikes** [comment]
@nguyenandi 

1. Remove the `.... codeblock:: console` from your file. That's a rendering error on the readthedocs.
2. Try using the relative path. Instead of `/data/CamCAN/BIDS/sub-CC110033` use just `sub-CC110033`.

I can't tell if `cubids-purge` will operate at the directory level. You may just need to manually remove those folders.

**Comment by scovitz** [comment]
Hi @araikes @nguyenandi Appologies for the delay on this. `cubids-purge` currently operates at the level of files not directories. With that in mind, @nguyenandi your dwi_purge.txt needs to specify filepaths rather than subject level directory names. Additionally, you should definitely remove `.... codeblock:: console` from the first line, as @araikes suggested, as that will cause an error.  See below for an example of what no_dwi.txt should look like: 

/Users/scovitz/CuBIDS_Test/BIDS_Dataset_DataLad/sub-01/ses-phdiff/dwi/sub-01_ses-phdiff_dwi.nii.gz
/Users/scovitz/CuBIDS_Test/BIDS_Dataset_DataLad/sub-02/ses-phdiff/dwi/sub-02_ses-phdiff_dwi.nii.gz
/Users/scovitz/CuBIDS_Test/BIDS_Dataset_DataLad/sub-03/ses-phdiff/dwi/sub-03_ses-phdiff_dwi.nii.gz

**Comment by scovitz** [comment]
Additionally @nguyenandi just in case you haven't already seen these, if you want more info on how each CLI program works, definitely reference our [NeuroImage pape](https://www.sciencedirect.com/science/article/pii/S1053811922007248)r : and [readthedocs page](https://cubids.readthedocs.io/en/latest/index.html) (which includes an example walkthrough)

**Comment by nguyenandi** [comment]
Thank you so much @scovitz and @araikes . Our team will try and let you know.
