### ISSUE TITLE
cubids command not found error

### ISSUE THREAD

**Issue by Arshitha** [PennLINC/CuBIDS#309]
## Summary
Hi there - I followed the installation instructions at https://cubids.readthedocs.io/en/latest/installation.html install cubids in a new conda environment but after installation I'm unable to use cubids as instructed. 

## Additional details

- CuBIDS version: v1.0.9

### What were you trying to do?

Installation commands I used: 

```bash
conda create -n cubids python=3.8 pip
conda activate cubids
pip install CuBIDS
```
and when I ran the following command I received "command not found" error

```bash
(cubids)[arshithab@cn4287]$ cubids -h
bash: cubids: command not found
(cubids)[arshithab@cn4287]$ cubids --help
bash: cubids: command not found
(cubids)[arshithab@cn4287]$ cubids validate -h
bash: cubids: command not found
(cubids)[arshithab@cn4287]$ 

```
### What did you expect to happen?
To print cubids help prompt or run the validate command

**Comment by tsalo** [comment]
@Arshitha I'm sorry, I never got a notification about this issue. The problem is that you have installed an older version of CuBIDS than the version in the documentation. We need to (1) release the newest version and (2) start building the documentation for older versions of CuBIDS.

@mattcieslak can you add me as an admin for the CuBIDS ReadTheDocs site?

**Comment by Arshitha** [comment]
@tsalo No worries, I figured that there was a mismatch between documentation and GitHub release. Building it from source worked for me! I'm guessing you have some action planned for this issue so I'll let you close it. Thanks!
